<a href="https://colab.research.google.com/github/andradenathan/algebra-linear-algoritmica-2023-2/blob/main/decomposicao_QR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Implementação do Algoritmo de Decomposição QR

Nome: Nathan Andrade dos Santos Lobo

DRE: 120082390

In [ ]:
import numpy as np
from math import sqrt

def decomposicao_QR(A):
  m, n = A.shape
  Q = np.zeros((m, n))
  R = np.zeros((n, n))

  # repete execução do gram schmidt só que salvando o
  # prod. interno na matriz R
  for i in range(n):
    w_i = A[:, i]
    for j in range(i):
      R[j, i] = np.dot(Q[:, j], A[:,i])
      w_i = w_i - (R[j, i] * Q[:, j])

    R[i, i] = np.linalg.norm(w_i)
    Q[:, i] = w_i / R[i, i]

  return Q, R

In [ ]:
A = np.array([
    [1., 2., 1.],
    [1., 0., 0.],
    [0., 1., 0.],
    [0., 0., 1.]
])

Q, R = decomposicao_QR(A)

print("Q:")
print(Q)

print("-------")

print("R:")
print(R)

Q:
[[ 0.70710678  0.57735027  0.15430335]
 [ 0.70710678 -0.57735027 -0.15430335]
 [ 0.          0.57735027 -0.3086067 ]
 [ 0.          0.          0.9258201 ]]
-------
R:
[[1.41421356 1.41421356 0.70710678]
 [0.         1.73205081 0.57735027]
 [0.         0.         1.08012345]]
